// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/workshops": {
    params: {};
  };
  "/workshops/:id": {
    params: {
      "id": string;
    };
  };
  "/workshops/new": {
    params: {};
  };
  "/workshops/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/checkout/:bookingId": {
    params: {
      "bookingId": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/profile/bookings": {
    params: {};
  };
  "/profile/saved": {
    params: {};
  };
  "/profile/workshops": {
    params: {};
  };
  "/profile/settings": {
    params: {};
  };
  "/api/wishlist/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/reviews/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/book/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/become-host": {
    params: {};
  };
  "/api/workshops": {
    params: {};
  };
  "/api/workshops/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/profile": {
    params: {};
  };
  "/api/profile/delete": {
    params: {};
  };
  "/api/profile/export": {
    params: {};
  };
  "/api/workshops/:workshopId/status": {
    params: {
      "workshopId": string;
    };
  };
  "/api/bookings/:bookingId/cancel": {
    params: {
      "bookingId": string;
    };
  };
  "/api/bookings/:bookingId/confirm": {
    params: {
      "bookingId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/workshops" | "/workshops/:id" | "/workshops/new" | "/workshops/:id/edit" | "/login" | "/register" | "/logout" | "/onboarding" | "/checkout/:bookingId" | "/profile" | "/profile/bookings" | "/profile/saved" | "/profile/workshops" | "/profile/settings" | "/api/wishlist/:workshopId" | "/api/reviews/:workshopId" | "/api/book/:workshopId" | "/api/become-host" | "/api/workshops" | "/api/workshops/:workshopId" | "/api/profile" | "/api/profile/delete" | "/api/profile/export" | "/api/workshops/:workshopId/status" | "/api/bookings/:bookingId/cancel" | "/api/bookings/:bookingId/confirm";
  };
  "routes/workshops.tsx": {
    id: "routes/workshops";
    page: "/workshops";
  };
  "routes/workshops.$id.tsx": {
    id: "routes/workshops.$id";
    page: "/workshops/:id";
  };
  "routes/workshops.new.tsx": {
    id: "routes/workshops.new";
    page: "/workshops/new";
  };
  "routes/workshops.$id.edit.tsx": {
    id: "routes/workshops.$id.edit";
    page: "/workshops/:id/edit";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/checkout.$bookingId.tsx": {
    id: "routes/checkout.$bookingId";
    page: "/checkout/:bookingId";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile" | "/profile/bookings" | "/profile/saved" | "/profile/workshops" | "/profile/settings";
  };
  "routes/profile._index.tsx": {
    id: "routes/profile._index";
    page: "/profile";
  };
  "routes/profile.bookings.tsx": {
    id: "routes/profile.bookings";
    page: "/profile/bookings";
  };
  "routes/profile.saved.tsx": {
    id: "routes/profile.saved";
    page: "/profile/saved";
  };
  "routes/profile.workshops.tsx": {
    id: "routes/profile.workshops";
    page: "/profile/workshops";
  };
  "routes/profile.settings.tsx": {
    id: "routes/profile.settings";
    page: "/profile/settings";
  };
  "routes/api.wishlist.$workshopId.tsx": {
    id: "routes/api.wishlist.$workshopId";
    page: "/api/wishlist/:workshopId";
  };
  "routes/api.reviews.$workshopId.tsx": {
    id: "routes/api.reviews.$workshopId";
    page: "/api/reviews/:workshopId";
  };
  "routes/api.book.$workshopId.tsx": {
    id: "routes/api.book.$workshopId";
    page: "/api/book/:workshopId";
  };
  "routes/api.become-host.tsx": {
    id: "routes/api.become-host";
    page: "/api/become-host";
  };
  "routes/api.workshops.tsx": {
    id: "routes/api.workshops";
    page: "/api/workshops";
  };
  "routes/api.workshops.$workshopId.tsx": {
    id: "routes/api.workshops.$workshopId";
    page: "/api/workshops/:workshopId";
  };
  "routes/api.profile.tsx": {
    id: "routes/api.profile";
    page: "/api/profile";
  };
  "routes/api.profile.delete.tsx": {
    id: "routes/api.profile.delete";
    page: "/api/profile/delete";
  };
  "routes/api.profile.export.tsx": {
    id: "routes/api.profile.export";
    page: "/api/profile/export";
  };
  "routes/api.workshops.$workshopId.status.tsx": {
    id: "routes/api.workshops.$workshopId.status";
    page: "/api/workshops/:workshopId/status";
  };
  "routes/api.bookings.$bookingId.cancel.tsx": {
    id: "routes/api.bookings.$bookingId.cancel";
    page: "/api/bookings/:bookingId/cancel";
  };
  "routes/api.bookings.$bookingId.confirm.tsx": {
    id: "routes/api.bookings.$bookingId.confirm";
    page: "/api/bookings/:bookingId/confirm";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/workshops": typeof import("./app/routes/workshops.tsx");
  "routes/workshops.$id": typeof import("./app/routes/workshops.$id.tsx");
  "routes/workshops.new": typeof import("./app/routes/workshops.new.tsx");
  "routes/workshops.$id.edit": typeof import("./app/routes/workshops.$id.edit.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/checkout.$bookingId": typeof import("./app/routes/checkout.$bookingId.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/profile._index": typeof import("./app/routes/profile._index.tsx");
  "routes/profile.bookings": typeof import("./app/routes/profile.bookings.tsx");
  "routes/profile.saved": typeof import("./app/routes/profile.saved.tsx");
  "routes/profile.workshops": typeof import("./app/routes/profile.workshops.tsx");
  "routes/profile.settings": typeof import("./app/routes/profile.settings.tsx");
  "routes/api.wishlist.$workshopId": typeof import("./app/routes/api.wishlist.$workshopId.tsx");
  "routes/api.reviews.$workshopId": typeof import("./app/routes/api.reviews.$workshopId.tsx");
  "routes/api.book.$workshopId": typeof import("./app/routes/api.book.$workshopId.tsx");
  "routes/api.become-host": typeof import("./app/routes/api.become-host.tsx");
  "routes/api.workshops": typeof import("./app/routes/api.workshops.tsx");
  "routes/api.workshops.$workshopId": typeof import("./app/routes/api.workshops.$workshopId.tsx");
  "routes/api.profile": typeof import("./app/routes/api.profile.tsx");
  "routes/api.profile.delete": typeof import("./app/routes/api.profile.delete.tsx");
  "routes/api.profile.export": typeof import("./app/routes/api.profile.export.tsx");
  "routes/api.workshops.$workshopId.status": typeof import("./app/routes/api.workshops.$workshopId.status.tsx");
  "routes/api.bookings.$bookingId.cancel": typeof import("./app/routes/api.bookings.$bookingId.cancel.tsx");
  "routes/api.bookings.$bookingId.confirm": typeof import("./app/routes/api.bookings.$bookingId.confirm.tsx");
};