// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/workshops": {
    params: {};
  };
  "/workshops/:id": {
    params: {
      "id": string;
    };
  };
  "/api/wishlist/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/reviews/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/book/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/workshops" | "/workshops/:id" | "/api/wishlist/:workshopId" | "/api/reviews/:workshopId" | "/api/book/:workshopId";
  };
  "routes/workshops.tsx": {
    id: "routes/workshops";
    page: "/workshops";
  };
  "routes/workshops.$id.tsx": {
    id: "routes/workshops.$id";
    page: "/workshops/:id";
  };
  "routes/api.wishlist.$workshopId.tsx": {
    id: "routes/api.wishlist.$workshopId";
    page: "/api/wishlist/:workshopId";
  };
  "routes/api.reviews.$workshopId.tsx": {
    id: "routes/api.reviews.$workshopId";
    page: "/api/reviews/:workshopId";
  };
  "routes/api.book.$workshopId.tsx": {
    id: "routes/api.book.$workshopId";
    page: "/api/book/:workshopId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/workshops": typeof import("./app/routes/workshops.tsx");
  "routes/workshops.$id": typeof import("./app/routes/workshops.$id.tsx");
  "routes/api.wishlist.$workshopId": typeof import("./app/routes/api.wishlist.$workshopId.tsx");
  "routes/api.reviews.$workshopId": typeof import("./app/routes/api.reviews.$workshopId.tsx");
  "routes/api.book.$workshopId": typeof import("./app/routes/api.book.$workshopId.tsx");
};