// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/workshops": {
    params: {};
  };
  "/workshops/:id": {
    params: {
      "id": string;
    };
  };
  "/workshops/new": {
    params: {};
  };
  "/workshops/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/onboarding/success": {
    params: {};
  };
  "/checkout/:bookingId": {
    params: {
      "bookingId": string;
    };
  };
  "/hosts/:id": {
    params: {
      "id": string;
    };
  };
  "/profile": {
    params: {};
  };
  "/profile/bookings": {
    params: {};
  };
  "/profile/saved": {
    params: {};
  };
  "/profile/workshops": {
    params: {};
  };
  "/profile/settings": {
    params: {};
  };
  "/api/wishlist/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/reviews/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/book/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/become-host": {
    params: {};
  };
  "/api/workshops": {
    params: {};
  };
  "/api/workshops/:workshopId": {
    params: {
      "workshopId": string;
    };
  };
  "/api/workshops/:workshopId/conductors": {
    params: {
      "workshopId": string;
    };
  };
  "/api/users/lookup": {
    params: {};
  };
  "/api/profile": {
    params: {};
  };
  "/api/profile/delete": {
    params: {};
  };
  "/api/profile/export": {
    params: {};
  };
  "/api/workshops/:workshopId/status": {
    params: {
      "workshopId": string;
    };
  };
  "/api/bookings/:bookingId/cancel": {
    params: {
      "bookingId": string;
    };
  };
  "/api/bookings/:bookingId/confirm": {
    params: {
      "bookingId": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/guides/kleingewerbe": {
    params: {};
  };
  "/guides/plan-workshop": {
    params: {};
  };
  "/guides/find-location": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/teach": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/agb": {
    params: {};
  };
  "/datenschutz": {
    params: {};
  };
  "/impressum": {
    params: {};
  };
  "/widerruf": {
    params: {};
  };
  "/guidelines": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/workshops" | "/workshops/:id" | "/workshops/new" | "/workshops/:id/edit" | "/login" | "/register" | "/logout" | "/onboarding" | "/onboarding/success" | "/checkout/:bookingId" | "/hosts/:id" | "/profile" | "/profile/bookings" | "/profile/saved" | "/profile/workshops" | "/profile/settings" | "/api/wishlist/:workshopId" | "/api/reviews/:workshopId" | "/api/book/:workshopId" | "/api/become-host" | "/api/workshops" | "/api/workshops/:workshopId" | "/api/workshops/:workshopId/conductors" | "/api/users/lookup" | "/api/profile" | "/api/profile/delete" | "/api/profile/export" | "/api/workshops/:workshopId/status" | "/api/bookings/:bookingId/cancel" | "/api/bookings/:bookingId/confirm" | "/sitemap.xml" | "/robots.txt" | "/guides/kleingewerbe" | "/guides/plan-workshop" | "/guides/find-location" | "/about" | "/teach" | "/faq" | "/agb" | "/datenschutz" | "/impressum" | "/widerruf" | "/guidelines";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/workshops.tsx": {
    id: "routes/workshops";
    page: "/workshops";
  };
  "routes/workshops.$id.tsx": {
    id: "routes/workshops.$id";
    page: "/workshops/:id";
  };
  "routes/workshops.new.tsx": {
    id: "routes/workshops.new";
    page: "/workshops/new";
  };
  "routes/workshops.$id.edit.tsx": {
    id: "routes/workshops.$id.edit";
    page: "/workshops/:id/edit";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/onboarding.success.tsx": {
    id: "routes/onboarding.success";
    page: "/onboarding/success";
  };
  "routes/checkout.$bookingId.tsx": {
    id: "routes/checkout.$bookingId";
    page: "/checkout/:bookingId";
  };
  "routes/hosts.$id.tsx": {
    id: "routes/hosts.$id";
    page: "/hosts/:id";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile" | "/profile/bookings" | "/profile/saved" | "/profile/workshops" | "/profile/settings";
  };
  "routes/profile._index.tsx": {
    id: "routes/profile._index";
    page: "/profile";
  };
  "routes/profile.bookings.tsx": {
    id: "routes/profile.bookings";
    page: "/profile/bookings";
  };
  "routes/profile.saved.tsx": {
    id: "routes/profile.saved";
    page: "/profile/saved";
  };
  "routes/profile.workshops.tsx": {
    id: "routes/profile.workshops";
    page: "/profile/workshops";
  };
  "routes/profile.settings.tsx": {
    id: "routes/profile.settings";
    page: "/profile/settings";
  };
  "routes/api.wishlist.$workshopId.tsx": {
    id: "routes/api.wishlist.$workshopId";
    page: "/api/wishlist/:workshopId";
  };
  "routes/api.reviews.$workshopId.tsx": {
    id: "routes/api.reviews.$workshopId";
    page: "/api/reviews/:workshopId";
  };
  "routes/api.book.$workshopId.tsx": {
    id: "routes/api.book.$workshopId";
    page: "/api/book/:workshopId";
  };
  "routes/api.become-host.tsx": {
    id: "routes/api.become-host";
    page: "/api/become-host";
  };
  "routes/api.workshops.tsx": {
    id: "routes/api.workshops";
    page: "/api/workshops";
  };
  "routes/api.workshops.$workshopId.tsx": {
    id: "routes/api.workshops.$workshopId";
    page: "/api/workshops/:workshopId";
  };
  "routes/api.workshops.$workshopId.conductors.tsx": {
    id: "routes/api.workshops.$workshopId.conductors";
    page: "/api/workshops/:workshopId/conductors";
  };
  "routes/api.users.lookup.tsx": {
    id: "routes/api.users.lookup";
    page: "/api/users/lookup";
  };
  "routes/api.profile.tsx": {
    id: "routes/api.profile";
    page: "/api/profile";
  };
  "routes/api.profile.delete.tsx": {
    id: "routes/api.profile.delete";
    page: "/api/profile/delete";
  };
  "routes/api.profile.export.tsx": {
    id: "routes/api.profile.export";
    page: "/api/profile/export";
  };
  "routes/api.workshops.$workshopId.status.tsx": {
    id: "routes/api.workshops.$workshopId.status";
    page: "/api/workshops/:workshopId/status";
  };
  "routes/api.bookings.$bookingId.cancel.tsx": {
    id: "routes/api.bookings.$bookingId.cancel";
    page: "/api/bookings/:bookingId/cancel";
  };
  "routes/api.bookings.$bookingId.confirm.tsx": {
    id: "routes/api.bookings.$bookingId.confirm";
    page: "/api/bookings/:bookingId/confirm";
  };
  "routes/sitemap[.]xml.tsx": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/robots[.]txt.tsx": {
    id: "routes/robots[.]txt";
    page: "/robots.txt";
  };
  "routes/guides.kleingewerbe.tsx": {
    id: "routes/guides.kleingewerbe";
    page: "/guides/kleingewerbe";
  };
  "routes/guides.plan-workshop.tsx": {
    id: "routes/guides.plan-workshop";
    page: "/guides/plan-workshop";
  };
  "routes/guides.find-location.tsx": {
    id: "routes/guides.find-location";
    page: "/guides/find-location";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/teach.tsx": {
    id: "routes/teach";
    page: "/teach";
  };
  "routes/faq.tsx": {
    id: "routes/faq";
    page: "/faq";
  };
  "routes/agb.tsx": {
    id: "routes/agb";
    page: "/agb";
  };
  "routes/datenschutz.tsx": {
    id: "routes/datenschutz";
    page: "/datenschutz";
  };
  "routes/impressum.tsx": {
    id: "routes/impressum";
    page: "/impressum";
  };
  "routes/widerruf.tsx": {
    id: "routes/widerruf";
    page: "/widerruf";
  };
  "routes/guidelines.tsx": {
    id: "routes/guidelines";
    page: "/guidelines";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/workshops": typeof import("./app/routes/workshops.tsx");
  "routes/workshops.$id": typeof import("./app/routes/workshops.$id.tsx");
  "routes/workshops.new": typeof import("./app/routes/workshops.new.tsx");
  "routes/workshops.$id.edit": typeof import("./app/routes/workshops.$id.edit.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/onboarding.success": typeof import("./app/routes/onboarding.success.tsx");
  "routes/checkout.$bookingId": typeof import("./app/routes/checkout.$bookingId.tsx");
  "routes/hosts.$id": typeof import("./app/routes/hosts.$id.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/profile._index": typeof import("./app/routes/profile._index.tsx");
  "routes/profile.bookings": typeof import("./app/routes/profile.bookings.tsx");
  "routes/profile.saved": typeof import("./app/routes/profile.saved.tsx");
  "routes/profile.workshops": typeof import("./app/routes/profile.workshops.tsx");
  "routes/profile.settings": typeof import("./app/routes/profile.settings.tsx");
  "routes/api.wishlist.$workshopId": typeof import("./app/routes/api.wishlist.$workshopId.tsx");
  "routes/api.reviews.$workshopId": typeof import("./app/routes/api.reviews.$workshopId.tsx");
  "routes/api.book.$workshopId": typeof import("./app/routes/api.book.$workshopId.tsx");
  "routes/api.become-host": typeof import("./app/routes/api.become-host.tsx");
  "routes/api.workshops": typeof import("./app/routes/api.workshops.tsx");
  "routes/api.workshops.$workshopId": typeof import("./app/routes/api.workshops.$workshopId.tsx");
  "routes/api.workshops.$workshopId.conductors": typeof import("./app/routes/api.workshops.$workshopId.conductors.tsx");
  "routes/api.users.lookup": typeof import("./app/routes/api.users.lookup.tsx");
  "routes/api.profile": typeof import("./app/routes/api.profile.tsx");
  "routes/api.profile.delete": typeof import("./app/routes/api.profile.delete.tsx");
  "routes/api.profile.export": typeof import("./app/routes/api.profile.export.tsx");
  "routes/api.workshops.$workshopId.status": typeof import("./app/routes/api.workshops.$workshopId.status.tsx");
  "routes/api.bookings.$bookingId.cancel": typeof import("./app/routes/api.bookings.$bookingId.cancel.tsx");
  "routes/api.bookings.$bookingId.confirm": typeof import("./app/routes/api.bookings.$bookingId.confirm.tsx");
  "routes/sitemap[.]xml": typeof import("./app/routes/sitemap[.]xml.tsx");
  "routes/robots[.]txt": typeof import("./app/routes/robots[.]txt.tsx");
  "routes/guides.kleingewerbe": typeof import("./app/routes/guides.kleingewerbe.tsx");
  "routes/guides.plan-workshop": typeof import("./app/routes/guides.plan-workshop.tsx");
  "routes/guides.find-location": typeof import("./app/routes/guides.find-location.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/teach": typeof import("./app/routes/teach.tsx");
  "routes/faq": typeof import("./app/routes/faq.tsx");
  "routes/agb": typeof import("./app/routes/agb.tsx");
  "routes/datenschutz": typeof import("./app/routes/datenschutz.tsx");
  "routes/impressum": typeof import("./app/routes/impressum.tsx");
  "routes/widerruf": typeof import("./app/routes/widerruf.tsx");
  "routes/guidelines": typeof import("./app/routes/guidelines.tsx");
};